### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by btzy** [Ginden/Najtingalo#1]
The page freezes when I click "Run" in both Chrome and Firefox, even when I'm just running the default Hello World program.

**Comment by Ginden** [comment]
For some reason it doesn't work as intended, you are absolutely right.

I just debugged generated code with Chrome and it seems like `pointer` is set to `-3`. I will have a closer look at this.

**Comment by Ginden** [comment]
@btzy Fixed, [should work now](https://ginden.github.io/Najtingalo/).

**Comment by btzy** [comment]
Yes, it looks fixed :)
